### ISSUE TITLE
Worker not exiting cleanly?

### ISSUE THREAD

**Issue by arg0s** [zhangliyong/rq-gevent-worker#1]
Are there issues with workers not exiting cleanly?

Here's an example of what I see where I need to do a `kill -9` to quit.

<pre>
19:36:27 Moving job to failed queue.
Traceback (most recent call last):
  File "/Users/arg0s/Envs/wrkr/lib/python2.7/site-packages/gevent/hub.py", line 133, in handle
    self.handler(*self.args, **self.kwargs)
  File "/Users/arg0s/Envs/wrkr/lib/python2.7/site-packages/rq_gevent_worker.py", line 66, in request_stop
    raise StopRequested()
StopRequested
^C^C
</pre>

This seems to happen only if jobs fail. Otherwise, here's what i see:

<pre>
19:36:10 Warm shut down requested.
19:36:10 Stopping after all greenlets are finished. Press Ctrl+C again for a cold shutdown.
</pre>

**Comment by zhangliyong** [comment]
Do you mean `kill` instead of `kill -9` ? If you do `kill -9`, it will kill the process immediately without cleanup.

**Comment by arg0s** [comment]
Let me clarify..
In normal situations, works exit cleanly after we request a warm shutdown (as shown in the second example).
However, after a job fails, the warm shutdown sequence doesnt happen (as seen in the first example). I'm forced to kill with -9.
Hope this helps.

**Comment by zhangliyong** [comment]
Do you mean when a job failed the worker will stuck and ouput:

```
19:36:27 Moving job to failed queue.
Traceback (most recent call last):
  File "/Users/arg0s/Envs/wrkr/lib/python2.7/site-packages/gevent/hub.py", line 133, in handle
    self.handler(*self.args, **self.kwargs)
  File "/Users/arg0s/Envs/wrkr/lib/python2.7/site-packages/rq_gevent_worker.py", line 66, in request_stop
    raise StopRequested()
StopRequested
```

and even you press `Ctrl-C`, it will not exit.  I have tested with failed jobs, it works fine, maybe you can give me more information, like the failed job example.
